version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    networks:
      - mongo-compose-network
    volumes:
      - ./queries/:/queries
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - mongo-compose-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DATABASE_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DATABASE_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DATABASE_USERNAME:$DATABASE_PASSWORD@mongodb:$DATABASE_PORT

networks:
  mongo-compose-network:
    driver: bridge